-- Colors generated by noctalia (lua/matugen.lua); fall back when absent.
local ok, matugen = pcall(require, "matugen")
if ok then
  matugen.setup()
else
  vim.cmd.colorscheme("base16-gruvbox-dark-medium")
end
